//@version=6
indicator("Tuspe Special Mix", shorttitle="Tuspe", overlay=true, dynamic_requests=true)

prevHigh = high[1]
prevLow = low[1]
prevFullSize = math.abs(prevHigh - prevLow)
fullSize = math.abs(high - low)

// ----------
//  Moving Averages
// ----------

maGroup = "Moving Averages"
ma1_length = input.int(13, title="MA1 Length", minval=4, group=maGroup)
ma1_type = input.string("EMA", title="MA1 Type", options=["SMA", "EMA"], group=maGroup)
ma2_length = input.int(48, title="MA2 Length", minval=8, group=maGroup)
ma2_type = input.string("EMA", title="MA2 Type", options=["SMA", "EMA"], group=maGroup)
ma3_length = input.int(200, title="MA3 Length", minval=20, group=maGroup)
ma3_type = input.string("SMA", title="MA3 Type", options=["SMA", "EMA"], group=maGroup)

// Moving average calculation function
calculate_ma(ma_type, src, length) =>
    ma_type == "SMA" ? ta.sma(src, length) : ta.ema(src, length)

// Calculate the moving averages
ma1 = calculate_ma(ma1_type, close, ma1_length)
ma2 = calculate_ma(ma2_type, close, ma2_length)
ma3 = calculate_ma(ma3_type, close, ma3_length)

// Plot moving averages
plot(ma1, color=color.orange, linewidth=1, title="MA1")
plot(ma2, color=color.yellow, linewidth=2, title="MA2")
plot(ma3, color=color.white, linewidth=2, title="MA3")

// ----------
//  Inside Bar
// ----------

isInsideBar = barstate.isconfirmed and fullSize < prevFullSize and prevHigh > high and prevLow < low
barcolor(isInsideBar ? color.yellow : na, title="Inside Bar")

// ----------
//  Engulfing Settings
// ----------

engulfingGroup = "Engulfing Pattern"
maxWickPercent = input.float(5.0, title="Max Wick % (closing direction)", minval=0.0, maxval=20.0, group=engulfingGroup)
minBigger = input.float(1.0, title="Times bigger than previous", minval=0.0, maxval=3.0, group=engulfingGroup)

bool isBullishEngulfing = false
bool isBearishEngulfing = false

// ----------
// Pullback Strategy Logic
// ----------

var bool bullishCross = false
var bool bearishCross = false
var bool pullbackMarked = false
var bool executionMarked = false

// Variables to store the high/low of the pullback candle
var float pullbackValue = na

// Reset states if price closes against MA2 (i.e., trend invalidation)
if ta.cross(ma1, ma2)
    bullishCross := false
    bearishCross := false
    executionMarked := false
    pullbackMarked := false
    pullbackValue := na // Reset pullback high/low on trend
    isBullishEngulfing := false
    isBearishEngulfing := false
    if close > ma1
        bullishCross := true
    else if ma1 > close
        bearishCross := true

bool bullishPullback = false
if bullishCross and not pullbackMarked and open > close
    bullishPullback := true
    pullbackValue := high

bool bearishPullback = false
if bearishCross and not pullbackMarked and close > open
    bearishPullback := true
    pullbackValue := low

// Pullback is confirmed
if bullishPullback or bearishPullback
    pullbackMarked := true

bool bearishExecution = false
bool bullishExecution = false

if pullbackMarked and not executionMarked
    if bullishCross and close > open and close > pullbackValue
        bullishExecution := true
    if bearishCross and open > close and pullbackValue > close
        bearishExecution := true

    if not bullishExecution and not bearishExecution and math.abs(open - close) >= minBigger * prevFullSize

        // Wick size in direction of close
        topWick   = high - math.max(open, close)
        bottomWick = math.min(open, close) - low

        // Wick percentage in direction of close
        topWickPct = topWick / fullSize * 100
        bottomWickPct = bottomWick / fullSize * 100

        if bullishCross and close > open and topWickPct <= maxWickPercent
            bullishExecution := true
        else if bearishCross and open > close and bottomWickPct <= maxWickPercent
            bearishExecution := true

    if bullishExecution or bearishExecution
        executionMarked := true

// Plotting the signals
plotshape(bullishExecution, style=shape.triangleup, location=location.belowbar, color=color.white, size=size.tiny, title="Bullish Execution")
plotshape(bearishExecution, style=shape.triangledown, location=location.abovebar, color=color.white, size=size.tiny, title="Bearish Execution")

// ----------
//  Alerts
// ----------

alertcondition(bullishExecution or bearishExecution, title="Continuation", message="Price has return over moving average and pullback is most likely over. Good luck and happy trading!")
alertcondition(bullishExecution, title="Bullish Continuation", message="Possible bullish continuation after the pullback. Good luck and happy trading!")
alertcondition(bearishExecution, title="Bearish Continuation", message="Possible bearish continuation after the pullback. Good luck and happy trading!")

// Candle patterns
alertcondition(isInsideBar, title="Inside Bar", message="New Inside Bar detected!")