//@version=6
indicator("Tuspe Special Mix", shorttitle="Tuspe", overlay=true, dynamic_requests=true)

isClosed = barstate.isconfirmed
fullSize = high - low
prevHigh = high[1]
prevLow = low[1]
prevFullSize = prevHigh - prevLow

// ----------
//  Moving Averages
// ----------

maGroup = "Moving Averages"
ma1_length = input.int(9, title="MA1 Length", minval=1, group=maGroup)
ma1_type = input.string("SMA", title="MA1 Type", options=["SMA", "EMA"], group=maGroup)
ma2_length = input.int(20, title="MA2 Length", minval=1, group=maGroup)
ma2_type = input.string("SMA", title="MA2 Type", options=["SMA", "EMA"], group=maGroup)
ma3_length = input.int(200, title="MA3 Length", minval=1, group=maGroup)
ma3_type = input.string("SMA", title="MA3 Type", options=["SMA", "EMA"], group=maGroup)

// Moving average calculation function
calculate_ma(ma_type, src, length) =>
    ma_type == "SMA" ? ta.sma(src, length) : ta.ema(src, length)

// Calculate the moving averages
ma1 = calculate_ma(ma1_type, close, ma1_length)
ma2 = calculate_ma(ma2_type, close, ma2_length)
ma3 = calculate_ma(ma3_type, close, ma3_length)

// Plot moving averages
plot(ma1, color=color.orange, linewidth=1, title="MA1")
plot(ma2, color=color.yellow, linewidth=2, title="MA2")
plot(ma3, color=color.white, linewidth=3, title="MA3")

// ----------
//  Session VWAP
// ----------

plot(ta.vwap(close), title="Session VWAP", color=color.aqua, linewidth=3)

// ----------
//  Displacement
// ----------

// Displacement Indicator Logic
rangeType = input.string("Open to Close", "Range Type", options = ['Open to Close', 'High to Low'], group="Displacement")
devPeriod = input.int(100, minval = 1, title = "Deviation Period", group="Displacement")
devMultiplier = input.int(3, minval = 0, title = "Deviation Multiplier", group="Displacement")

priceRange = rangeType == "Open to Close" ? math.abs(open - close) : high - low
rangeDeviation = ta.stdev(priceRange, devPeriod) * devMultiplier

priceGap = close[1] > open[1] ? high[2] < low[0] : low[2] > high[0]
isDisplaced = priceRange[1] > rangeDeviation[1] and priceGap

barcolor(isDisplaced ? color.maroon : na, offset = -1, title="Displacement Highlight Color")
alertcondition(isDisplaced, title="Elephant Bar", message="New Displacement / Elephant Bar detected!")

// ----------
//  Inside Bar
// ----------

isInsideBar = isClosed and not isDisplaced and fullSize < prevFullSize and prevHigh > high and prevLow < low
barcolor(isInsideBar ? color.yellow : na, title="Inside Bar")
alertcondition(isInsideBar, title="Inside Bar", message="New Inside Bar detected!")
alertcondition(isInsideBar or isDisplaced, title="Elephant or Inside Bar", message="New interesting bar detected!")

// ----------
//  Outside Bar
// ----------

isOutsideBar = isClosed and not isDisplaced and not isInsideBar and fullSize > prevFullSize and prevHigh < high and prevLow > low
barcolor(isOutsideBar ? color.fuchsia : na, title="Outside Bar")
alertcondition(isOutsideBar, title="Outside Bar", message="New Outside Bar detected!")