//@version=5
indicator(title="Zero Lag MACD and RSI", shorttitle="Zero Lag MACD & RSI", overlay=false)

// MACD - Zero Lag Settings
source = close
fastLength = input.int(12, title="Fast MM period", minval=1)
slowLength = input.int(26, title="Slow MM period", minval=1)
signalLength = input.int(9, title="Signal MM period", minval=1)
MacdEmaLength = input.int(9, title="MACD EMA period", minval=1)
useEma = input.bool(true, title="Use EMA (otherwise SMA)")
useOldAlgo = input.bool(false, title="Use Glaz algo (otherwise 'real' original zero lag)")
showDots = input.bool(true, title="Show symbols to indicate crossing")
dotsDistance = input.float(1.5, title="Symbols distance factor", minval=0.1)
showCross = input.bool(true, title="Show Crosses")
crossUpColor = input.color(color.green, title="MACD Crossing Up Color")
crossDownColor = input.color(color.red, title="MACD Crossing Down Color")

// RSI Settings
rsiLengthInput = input.int(14, minval=1, title="RSI Length", group="RSI Settings")
rsiSourceInput = input.source(close, "Source", group="RSI Settings")
maTypeInput = input.string("SMA", title="MA Type", options=["SMA", "Bollinger Bands", "EMA", "SMMA (RMA)", "WMA", "VWMA"], group="MA Settings")
maLengthInput = input.int(14, title="MA Length", group="MA Settings")
bbMultInput = input.float(2.0, minval=0.001, maxval=50, title="BB StdDev", group="MA Settings")
showDivergence = input.bool(false, title="Show Divergence", group="RSI Settings", display = display.data_window)

// MACD Calculation
ma1 = useEma ? ta.ema(source, fastLength) : ta.sma(source, fastLength)
ma2 = useEma ? ta.ema(ma1, fastLength) : ta.sma(ma1, fastLength)
zerolagEMA = ((2 * ma1) - ma2)

mas1 = useEma ? ta.ema(source, slowLength) : ta.sma(source, slowLength)
mas2 = useEma ? ta.ema(mas1, slowLength) : ta.sma(mas1, slowLength)
zerolagslowMA = ((2 * mas1) - mas2)

ZeroLagMACD = zerolagEMA - zerolagslowMA
emasig1 = ta.ema(ZeroLagMACD, signalLength)
emasig2 = ta.ema(emasig1, signalLength)
signal = useOldAlgo ? ta.sma(ZeroLagMACD, signalLength) : (2 * emasig1) - emasig2
hist = ZeroLagMACD - signal

upHist = (hist > 0) ? hist : na
downHist = (hist <= 0) ? hist : na

// RSI Calculation
up = ta.rma(math.max(ta.change(rsiSourceInput), 0), rsiLengthInput)
down = ta.rma(-math.min(ta.change(rsiSourceInput), 0), rsiLengthInput)
rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - (100 / (1 + up / down))
rsiMA = switch maTypeInput
    "SMA" => ta.sma(rsi, maLengthInput)
    "EMA" => ta.ema(rsi, maLengthInput)
    "SMMA (RMA)" => ta.rma(rsi, maLengthInput)
    "WMA" => ta.wma(rsi, maLengthInput)
    "VWMA" => ta.vwma(rsi, maLengthInput)

// Plot MACD
p1 = plot(upHist, color=color.green, transp=40, style=plot.style_histogram, title='Positive delta')
p2 = plot(downHist, color=color.purple, transp=40, style=plot.style_histogram, title='Negative delta')
zeroLine = plot(ZeroLagMACD, color=color.black, linewidth=2, title='MACD line')
signalLine = plot(signal, color=color.gray, linewidth=2, title='Signal')
ribbonDiff = hist > 0 ? color.green : color.purple
fill(zeroLine, signalLine, color=ribbonDiff)
plot(ta.ema(ZeroLagMACD, MacdEmaLength), color=color.red, linewidth=2, title='EMA on MACD line')

// Plot RSI
rsiPlot = plot(rsi, "RSI", color=#7E57C2)
plot(rsiMA, "RSI-based MA", color=color.yellow)
rsiUpperBand = hline(70, "RSI Upper Band", color=#787B86)
rsiLowerBand = hline(30, "RSI Lower Band", color=#787B86)
fill(rsiUpperBand, rsiLowerBand, color=color.rgb(126, 87, 194, 90), title="RSI Background Fill")

// Crosses for MACD
crossUp = ta.cross(ZeroLagMACD, signal) and ZeroLagMACD > signal
crossDown = ta.cross(ZeroLagMACD, signal) and ZeroLagMACD < signal
plot(showCross and crossUp ? signal : na, title="Cross Up", style=plot.style_circles, linewidth=4, color=crossUpColor)
plot(showCross and crossDown ? signal : na, title="Cross Down", style=plot.style_circles, linewidth=4, color=crossDownColor)

// Divergence Logic (RSI)
lookbackRight = 5
lookbackLeft = 5
rangeUpper = 60
rangeLower = 5
bearColor = color.red
bullColor = color.green
textColor = color.white
noneColor = color.new(color.white, 100)

plFound = na(ta.pivotlow(rsi, lookbackLeft, lookbackRight)) ? false : true
phFound = na(ta.pivothigh(rsi, lookbackLeft, lookbackRight)) ? false : true
_inRange(cond) =>
    bars = ta.barssince(cond == true)
    rangeLower <= bars and bars <= rangeUpper

// Regular Bullish Divergence
rsiHL = rsi[lookbackRight] > ta.valuewhen(plFound, rsi[lookbackRight], 1) and _inRange(plFound[1])
priceLL = low[lookbackRight] < ta.valuewhen(plFound, low[lookbackRight], 1)
bullCondAlert = priceLL and rsiHL and plFound
bullCond = showDivergence and bullCondAlert

plot(plFound ? rsi[lookbackRight] : na, offset=-lookbackRight, title="Regular Bullish", linewidth=2, color=(bullCond ? bullColor : noneColor), display = display.pane)

// Regular Bearish Divergence
rsiLH = rsi[lookbackRight] < ta.valuewhen(phFound, rsi[lookbackRight], 1) and _inRange(phFound[1])
priceHH = high[lookbackRight] > ta.valuewhen(phFound, high[lookbackRight], 1)
bearCondAlert = priceHH and rsiLH and phFound
bearCond = showDivergence and bearCondAlert

plot(phFound ? rsi[lookbackRight] : na, offset=-lookbackRight, title="Regular Bearish", linewidth=2, color=(bearCond ? bearColor : noneColor), display = display.pane)

alertcondition(bullCondAlert, title='Regular Bullish Divergence', message="Found a new Regular Bullish Divergence.")
alertcondition(bearCondAlert, title='Regular Bearish Divergence', message='Found a new Regular Bearish Divergence.')
